name: Automated Salesforce Backup

on:
  workflow_dispatch:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli@7.209.6
          export PATH="/home/runner/.npm-global/bin:$PATH"
          sfdx --version
      
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
          sfdx force:auth:jwt:grant --client-id ${{ secrets.SF_CONSUMER_KEY }}   --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }}   --instance-url https://login.salesforce.com --set-default-dev-hub

      - name: Verify Authentication
        run: sfdx org:list
      
      - name: backup Salesforce Configuration
        run: |
          sfdx force:source:retrieve -p force-app -u kishorenate@gmail.com

      - name: Backup Salesforce data
        run: |
          mkdir -p data
          OBJECTS=$(sfdx force:data:soql:query -q "SELECT QualifiedApiName FROM EntityDefinition WHERE IsCustomSetting = FALSE AND IsEverCreatable = TRUE" --target-org ${{ secrets.SF_USERNAME }} --json | jq -r '.result.records[].QualifiedApiName')
          for OBJECT in $OBJECTS; do
              echo "Backing up: $OBJECT"
              FIELDS=$(sfdx force:data:soql:query -q "SELECT QualifiedApiName FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = '$OBJECT'" --target-org ${{ secrets.SF_USERNAME }} --json | jq -r '.result.records[].QualifiedApiName' | paste -sd "," -)
              if [ -n "$FIELDS" ]; then
                  sfdx force:data:tree:export -q "SELECT $FIELDS FROM $OBJECT" -d ./data --target-org ${{ secrets.SF_USERNAME }}
              else
                  echo "Skipping $OBJECT (No fields found)"
              fi
          done
          echo "Backup completed!"
