name: Salesforce Deployment

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Salesforce CLI
      #   run: |
      #     curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-x64.tar.xz -o sfdx.tar.xz
      #     tar xvf sfdx.tar.xz
      #     ./sfdx/install

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli
      
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
          sfdx force:auth:jwt:grant --client-id 3MVG9PwZx9R6_UrfM1s1WcZIK1oJv7XQ5FnHly3lcJ_gLADFHRF27x7rtBA2xaZXKsmsbS6Ujj8ASgmkPgp4H   --jwt-key-file server.key --username kishorenate@gmail.com   --instance-url https://login.salesforce.com --set-default-dev-hub

      - name: Verify Authentication
        run: sfdx force:org:display
      
      - name: Retrieve Salesforce Metadata
        run: |
          sfdx force:source:retrieve --manifest package.xml

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy --manifest package.xml --testlevel RunLocalTests
