name: Salesforce Deployment

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Salesforce CLI
      #   run: |
      #     curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-x64.tar.xz -o sfdx.tar.xz
      #     tar xvf sfdx.tar.xz
      #     ./sfdx/install

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli@7.209.6
          export PATH="/home/runner/.npm-global/bin:$PATH"
          sfdx --version
      
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
          sfdx force:auth:jwt:grant --client-id ${{ secrets.SF_CONSUMER_KEY }}   --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }}   --instance-url https://login.salesforce.com --set-default-dev-hub

      - name: Verify Authentication
        run: sfdx org:list
      
      - name: Retrieve Salesforce Metadata
        run: |
          sfdx force:source:retrieve -m CustomObject -u kishorenate@gmail.com

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u kishorenate@gmail.com
